name = "Brassworks"
author = "RacingWither and night_light7665"
version = "1.0.7d"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c80d10251a67b2769baf30fb9f8ddf10aa78869d7403cd40577225bed5346db"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
