name = "Brassworks"
author = "RacingWither and night_light7665"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13c577966d4925fdc5e471a7d5c1221374c1f48d812531b8a93fe20de9c31f48"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
