name = "Brassworks"
author = "RacingWither and night_light7665"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10e54fc90770362421b54eb9538904f6563f820e692253c682ccabd045389834"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
