name = "Brassworks"
author = "RacingWither and night_light7665"
version = "0.1.2"
pack-format = "packwiz:1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60321d4efebf4373b294e5bd4f02ee8a4ccac1495418fee72340253853e59cea"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
