name = "Brassworks"
author = "RacingWither and night_light7665"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19f390f4dba3c074777e08a895cd757e517299a3191756ec5454fb6a86ce4222"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
