name = "Brassworks"
author = "RacingWither and night_light7665"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76c512ff035d318383d2204f73ca5dc3acd8f54f5247625788c49a5329594b76"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
