name = "Brassworks"
author = "RacingWither and night_light7665"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e469db47eff145874850317aa76e9257575ba447e80eabb6f617fd64d6d5a23"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
