name = "Brassworks"
author = "RacingWither and night_light7665"
version = "1.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5bbfd651304f1da94dfac2864dad258aad57ccd21a00aace5bf18c4b162f469a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
