name = "Brassworks"
author = "RacingWither and night_light7665"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55813e73aa85f9af3286c0bda4251c817379ac7054f002683ec411c0f23e5236"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
