name = "Brassworks"
author = "RacingWither and night_light7665"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8186e344498954d38a346a5b302599779daf935fdabafe63ed2368a6318251c6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
