name = "Brassworks"
author = "RacingWither and night_light7665"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "432b7f11ffd5affa4c6f66d030173696c6f90ed8bd8849a2fd0b927b91e1a9d4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
