name = "Brassworks"
author = "RacingWither and night_light7665"
version = "0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e91faea4e25e8e86f693f9b525e27e67f5207c2a0f0f4676105d55d7f3385b1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
