name = "Brassworks"
author = "RacingWither and night_light7665"
version = "0.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3369fcefda086feb727b2000cd2ec323000bdd4d3227891bb0508b86085d4c95"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
