name = "Brassworks"
author = "RacingWither and night_light7665"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9942c211cea10b3bf2d098890874575da5230f361c3eecff49f466490a23bbe7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
